vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    products:
      uri_prefix: /images/gites
      upload_destination: "%kernel.project_dir%/public/images/gites"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
